[2022-06-20 01:38:08,515] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures manual__2022-06-20T01:38:05.018482+00:00 [queued]>
[2022-06-20 01:38:08,521] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures manual__2022-06-20T01:38:05.018482+00:00 [queued]>
[2022-06-20 01:38:08,522] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:38:08,523] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:38:08,524] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:38:08,534] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_pictures> on 2022-06-20 01:38:05.018482+00:00
[2022-06-20 01:38:08,539] {standard_task_runner.py:52} INFO - Started process 714 to run task
[2022-06-20 01:38:08,542] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'manual__2022-06-20T01:38:05.018482+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/data-pipline-book/2_1_download_rocket_launches.py', '--cfg-path', '/tmp/tmpox86g77f', '--error-file', '/tmp/tmp2vrd3iwl']
[2022-06-20 01:38:08,545] {standard_task_runner.py:80} INFO - Job 113: Subtask get_pictures
[2022-06-20 01:38:08,598] {task_command.py:369} INFO - Running <TaskInstance: download_rocket_launches.get_pictures manual__2022-06-20T01:38:05.018482+00:00 [running]> on host b8db81cc5447
[2022-06-20 01:38:08,678] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2022-06-20T01:38:05.018482+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-20T01:38:05.018482+00:00
[2022-06-20 01:38:08,681] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data-pipline-book/2_1_download_rocket_launches.py", line 40, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2022-06-20 01:38:08,692] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20220620T013805, start_date=20220620T013808, end_date=20220620T013808
[2022-06-20 01:38:08,701] {standard_task_runner.py:97} ERROR - Failed to execute job 113 for task get_pictures ('results'; 714)
[2022-06-20 01:38:08,716] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:38:08,745] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
