[2022-06-20 01:34:20,325] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 3_1_scheduled_dag.fetch_events scheduled__2019-01-04T00:00:00+00:00 [queued]>
[2022-06-20 01:34:20,350] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 3_1_scheduled_dag.fetch_events scheduled__2019-01-04T00:00:00+00:00 [queued]>
[2022-06-20 01:34:20,355] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:20,363] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:34:20,366] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:20,386] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): fetch_events> on 2019-01-04 00:00:00+00:00
[2022-06-20 01:34:20,396] {standard_task_runner.py:52} INFO - Started process 179 to run task
[2022-06-20 01:34:20,400] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '3_1_scheduled_dag', 'fetch_events', 'scheduled__2019-01-04T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/data-pipline-book/3_1_scheduled_dag.py', '--cfg-path', '/tmp/tmp99g2141p', '--error-file', '/tmp/tmpw7byjr0i']
[2022-06-20 01:34:20,405] {standard_task_runner.py:80} INFO - Job 26: Subtask fetch_events
[2022-06-20 01:34:20,478] {task_command.py:369} INFO - Running <TaskInstance: 3_1_scheduled_dag.fetch_events scheduled__2019-01-04T00:00:00+00:00 [running]> on host b8db81cc5447
[2022-06-20 01:34:20,565] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=3_1_scheduled_dag
AIRFLOW_CTX_TASK_ID=fetch_events
AIRFLOW_CTX_EXECUTION_DATE=2019-01-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-04T00:00:00+00:00
[2022-06-20 01:34:20,568] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-20 01:34:20,573] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p /data/events && curl -o /data/events.json http://events_api:5000/events']
[2022-06-20 01:34:20,592] {subprocess.py:85} INFO - Output:
[2022-06-20 01:34:20,598] {subprocess.py:92} INFO - mkdir: cannot create directory ‘/data’: Permission denied
[2022-06-20 01:34:20,601] {subprocess.py:96} INFO - Command exited with return code 1
[2022-06-20 01:34:20,626] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-06-20 01:34:20,634] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=3_1_scheduled_dag, task_id=fetch_events, execution_date=20190104T000000, start_date=20220620T013420, end_date=20220620T013420
[2022-06-20 01:34:20,671] {standard_task_runner.py:97} ERROR - Failed to execute job 26 for task fetch_events (Bash command failed. The command returned a non-zero exit code 1.; 179)
[2022-06-20 01:34:20,698] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:34:20,747] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
