[2022-06-20 01:34:21,220] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 3_1_scheduled_dag.fetch_events scheduled__2019-01-05T00:00:00+00:00 [queued]>
[2022-06-20 01:34:21,236] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 3_1_scheduled_dag.fetch_events scheduled__2019-01-05T00:00:00+00:00 [queued]>
[2022-06-20 01:34:21,238] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:21,240] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:34:21,242] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:21,277] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): fetch_events> on 2019-01-05 00:00:00+00:00
[2022-06-20 01:34:21,289] {standard_task_runner.py:52} INFO - Started process 195 to run task
[2022-06-20 01:34:21,318] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '3_1_scheduled_dag', 'fetch_events', 'scheduled__2019-01-05T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/data-pipline-book/3_1_scheduled_dag.py', '--cfg-path', '/tmp/tmpmfm5yqwg', '--error-file', '/tmp/tmpp7xgbtev']
[2022-06-20 01:34:21,327] {standard_task_runner.py:80} INFO - Job 31: Subtask fetch_events
[2022-06-20 01:34:21,413] {task_command.py:369} INFO - Running <TaskInstance: 3_1_scheduled_dag.fetch_events scheduled__2019-01-05T00:00:00+00:00 [running]> on host b8db81cc5447
[2022-06-20 01:34:21,522] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=3_1_scheduled_dag
AIRFLOW_CTX_TASK_ID=fetch_events
AIRFLOW_CTX_EXECUTION_DATE=2019-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-05T00:00:00+00:00
[2022-06-20 01:34:21,527] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-20 01:34:21,529] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p /data/events && curl -o /data/events.json http://events_api:5000/events']
[2022-06-20 01:34:21,573] {subprocess.py:85} INFO - Output:
[2022-06-20 01:34:21,575] {subprocess.py:92} INFO - mkdir: cannot create directory ‘/data’: Permission denied
[2022-06-20 01:34:21,577] {subprocess.py:96} INFO - Command exited with return code 1
[2022-06-20 01:34:21,599] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-06-20 01:34:21,604] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=3_1_scheduled_dag, task_id=fetch_events, execution_date=20190105T000000, start_date=20220620T013421, end_date=20220620T013421
[2022-06-20 01:34:21,660] {standard_task_runner.py:97} ERROR - Failed to execute job 31 for task fetch_events (Bash command failed. The command returned a non-zero exit code 1.; 195)
[2022-06-20 01:34:21,682] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:34:21,738] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
