[2022-06-14 18:22:21,888] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-14T17:00:00+00:00 [queued]>
[2022-06-14 18:22:21,893] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-14T17:00:00+00:00 [queued]>
[2022-06-14 18:22:21,894] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 18:22:21,894] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-14 18:22:21,896] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 18:22:21,917] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data> on 2022-06-14 17:00:00+00:00
[2022-06-14 18:22:21,927] {standard_task_runner.py:52} INFO - Started process 74131 to run task
[2022-06-14 18:22:21,934] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'listing_4_05', 'get_data', 'scheduled__2022-06-14T17:00:00+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/listing_4_5.py', '--cfg-path', '/tmp/tmpuncqim1q', '--error-file', '/tmp/tmp7f3vqxao']
[2022-06-14 18:22:21,936] {standard_task_runner.py:80} INFO - Job 157: Subtask get_data
[2022-06-14 18:22:22,022] {task_command.py:369} INFO - Running <TaskInstance: listing_4_05.get_data scheduled__2022-06-14T17:00:00+00:00 [running]> on host 48de8cc79e8d
[2022-06-14 18:22:22,113] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=listing_4_05
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-14T17:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-14T17:00:00+00:00
[2022-06-14 18:22:22,118] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-06-14 23:53:18,528] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/listing_4_5.py", line 21, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/local/lib/python3.7/urllib/request.py", line 288, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 1130165 out of 57911039 bytes>
[2022-06-14 23:53:18,570] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=listing_4_05, task_id=get_data, execution_date=20220614T170000, start_date=20220614T182221, end_date=20220614T235318
[2022-06-14 23:53:18,587] {standard_task_runner.py:97} ERROR - Failed to execute job 157 for task get_data (<urlopen error retrieval incomplete: got only 1130165 out of 57911039 bytes>; 74131)
[2022-06-14 23:53:18,638] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-14 23:53:18,656] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
