[2022-06-14 15:04:46,439] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-14T14:00:00+00:00 [queued]>
[2022-06-14 15:04:46,459] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-14T14:00:00+00:00 [queued]>
[2022-06-14 15:04:46,461] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 15:04:46,463] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-14 15:04:46,465] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 15:04:46,495] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data> on 2022-06-14 14:00:00+00:00
[2022-06-14 15:04:46,515] {standard_task_runner.py:52} INFO - Started process 74065 to run task
[2022-06-14 15:04:46,521] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'listing_4_05', 'get_data', 'scheduled__2022-06-14T14:00:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/listing_4_5.py', '--cfg-path', '/tmp/tmp61ymr9ie', '--error-file', '/tmp/tmp9cafi35l']
[2022-06-14 15:04:46,526] {standard_task_runner.py:80} INFO - Job 154: Subtask get_data
[2022-06-14 15:04:46,692] {task_command.py:369} INFO - Running <TaskInstance: listing_4_05.get_data scheduled__2022-06-14T14:00:00+00:00 [running]> on host 48de8cc79e8d
[2022-06-14 15:04:46,790] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=listing_4_05
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-14T14:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-14T14:00:00+00:00
[2022-06-14 15:04:46,795] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-06-14 21:08:00,352] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-06-14 21:08:00,358] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 74065. PIDs of all processes in the group: [74065]
[2022-06-14 21:08:00,361] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 74065
[2022-06-14 21:08:00,367] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-06-14 21:08:00,422] {process_utils.py:75} INFO - Process psutil.Process(pid=74065, status='terminated', exitcode=0, started='15:04:46') (74065) terminated with exit code 0
