[2022-06-13 00:00:00,586] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-12T23:00:00+00:00 [queued]>
[2022-06-13 00:00:00,592] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-12T23:00:00+00:00 [queued]>
[2022-06-13 00:00:00,593] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 00:00:00,595] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-13 00:00:00,595] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 00:00:00,607] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data> on 2022-06-12 23:00:00+00:00
[2022-06-13 00:00:00,612] {standard_task_runner.py:52} INFO - Started process 797 to run task
[2022-06-13 00:00:00,615] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'listing_4_05', 'get_data', 'scheduled__2022-06-12T23:00:00+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/listing_4_5.py', '--cfg-path', '/tmp/tmpxjr84ozu', '--error-file', '/tmp/tmpsubsroet']
[2022-06-13 00:00:00,617] {standard_task_runner.py:80} INFO - Job 114: Subtask get_data
[2022-06-13 00:00:00,669] {task_command.py:369} INFO - Running <TaskInstance: listing_4_05.get_data scheduled__2022-06-12T23:00:00+00:00 [running]> on host 48de8cc79e8d
[2022-06-13 00:00:00,717] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=listing_4_05
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-12T23:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-12T23:00:00+00:00
[2022-06-13 00:00:00,719] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-06-13 00:00:01,780] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/listing_4_5.py", line 21, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/local/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2022-06-13 00:00:01,805] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=listing_4_05, task_id=get_data, execution_date=20220612T230000, start_date=20220613T000000, end_date=20220613T000001
[2022-06-13 00:00:01,820] {standard_task_runner.py:97} ERROR - Failed to execute job 114 for task get_data (HTTP Error 404: Not Found; 797)
[2022-06-13 00:00:01,854] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-13 00:00:01,878] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
