[2022-06-12 23:47:59,383] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-11T20:00:00+00:00 [queued]>
[2022-06-12 23:47:59,404] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-11T20:00:00+00:00 [queued]>
[2022-06-12 23:47:59,407] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 23:47:59,409] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-12 23:47:59,413] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 23:47:59,441] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data> on 2022-06-11 20:00:00+00:00
[2022-06-12 23:47:59,448] {standard_task_runner.py:52} INFO - Started process 122 to run task
[2022-06-12 23:47:59,453] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'listing_4_05', 'get_data', 'scheduled__2022-06-11T20:00:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/listing_4_5.py', '--cfg-path', '/tmp/tmp8z0ny4w4', '--error-file', '/tmp/tmpl4kmt3jc']
[2022-06-12 23:47:59,456] {standard_task_runner.py:80} INFO - Job 86: Subtask get_data
[2022-06-12 23:47:59,549] {task_command.py:369} INFO - Running <TaskInstance: listing_4_05.get_data scheduled__2022-06-11T20:00:00+00:00 [running]> on host 48de8cc79e8d
[2022-06-12 23:47:59,607] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=listing_4_05
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-11T20:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-11T20:00:00+00:00
[2022-06-12 23:47:59,610] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-06-12 23:48:00,228] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/listing_4_5.py", line 21, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/local/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2022-06-12 23:48:00,251] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=listing_4_05, task_id=get_data, execution_date=20220611T200000, start_date=20220612T234759, end_date=20220612T234800
[2022-06-12 23:48:00,266] {standard_task_runner.py:97} ERROR - Failed to execute job 86 for task get_data (HTTP Error 503: Service Temporarily Unavailable; 122)
[2022-06-12 23:48:00,327] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-12 23:48:00,365] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
