[2022-06-13 12:00:00,484] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-13T11:00:00+00:00 [queued]>
[2022-06-13 12:00:00,490] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-13T11:00:00+00:00 [queued]>
[2022-06-13 12:00:00,491] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 12:00:00,492] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-13 12:00:00,493] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 12:00:00,501] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data> on 2022-06-13 11:00:00+00:00
[2022-06-13 12:00:00,504] {standard_task_runner.py:52} INFO - Started process 29963 to run task
[2022-06-13 12:00:00,507] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'listing_4_05', 'get_data', 'scheduled__2022-06-13T11:00:00+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/listing_4_5.py', '--cfg-path', '/tmp/tmpto3zno_f', '--error-file', '/tmp/tmp7aprpkwa']
[2022-06-13 12:00:00,507] {standard_task_runner.py:80} INFO - Job 126: Subtask get_data
[2022-06-13 12:00:00,545] {task_command.py:369} INFO - Running <TaskInstance: listing_4_05.get_data scheduled__2022-06-13T11:00:00+00:00 [running]> on host 48de8cc79e8d
[2022-06-13 12:00:00,586] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=listing_4_05
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-13T11:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-13T11:00:00+00:00
[2022-06-13 12:00:00,588] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-06-13 12:06:47,916] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-06-13 12:06:47,920] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 29963. PIDs of all processes in the group: [29963]
[2022-06-13 12:06:47,922] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 29963
[2022-06-13 12:06:47,926] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-06-13 12:06:47,990] {process_utils.py:75} INFO - Process psutil.Process(pid=29963, status='terminated', exitcode=0, started='12:00:00') (29963) terminated with exit code 0
