[2022-06-14 22:32:14,468] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-14T21:00:00+00:00 [queued]>
[2022-06-14 22:32:14,485] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-14T21:00:00+00:00 [queued]>
[2022-06-14 22:32:14,487] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 22:32:14,490] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-14 22:32:14,492] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 22:32:14,510] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data> on 2022-06-14 21:00:00+00:00
[2022-06-14 22:32:14,518] {standard_task_runner.py:52} INFO - Started process 74209 to run task
[2022-06-14 22:32:14,524] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'listing_4_05', 'get_data', 'scheduled__2022-06-14T21:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/listing_4_5.py', '--cfg-path', '/tmp/tmpml0ai21n', '--error-file', '/tmp/tmp066_h1ig']
[2022-06-14 22:32:14,529] {standard_task_runner.py:80} INFO - Job 161: Subtask get_data
[2022-06-14 22:32:14,636] {task_command.py:369} INFO - Running <TaskInstance: listing_4_05.get_data scheduled__2022-06-14T21:00:00+00:00 [running]> on host 48de8cc79e8d
[2022-06-14 22:32:14,773] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=listing_4_05
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-14T21:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-14T21:00:00+00:00
[2022-06-14 22:32:14,778] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-06-14 23:54:49,204] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/listing_4_5.py", line 21, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/local/lib/python3.7/urllib/request.py", line 288, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 687797 out of 55654098 bytes>
[2022-06-14 23:54:49,244] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=listing_4_05, task_id=get_data, execution_date=20220614T210000, start_date=20220614T223214, end_date=20220614T235449
[2022-06-14 23:54:49,264] {standard_task_runner.py:97} ERROR - Failed to execute job 161 for task get_data (<urlopen error retrieval incomplete: got only 687797 out of 55654098 bytes>; 74209)
[2022-06-14 23:54:49,305] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-14 23:54:49,326] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
