[2022-06-20 01:34:20,010] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 3_1_scheduled_dag.fetch_events scheduled__2019-01-03T00:00:00+00:00 [queued]>
[2022-06-20 01:34:20,019] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 3_1_scheduled_dag.fetch_events scheduled__2019-01-03T00:00:00+00:00 [queued]>
[2022-06-20 01:34:20,021] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:20,022] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:34:20,025] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:20,055] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): fetch_events> on 2019-01-03 00:00:00+00:00
[2022-06-20 01:34:20,061] {standard_task_runner.py:52} INFO - Started process 173 to run task
[2022-06-20 01:34:20,065] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '3_1_scheduled_dag', 'fetch_events', 'scheduled__2019-01-03T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/data-pipline-book/3_1_scheduled_dag.py', '--cfg-path', '/tmp/tmpkc4c00xm', '--error-file', '/tmp/tmp6l7ws01k']
[2022-06-20 01:34:20,069] {standard_task_runner.py:80} INFO - Job 24: Subtask fetch_events
[2022-06-20 01:34:20,125] {task_command.py:369} INFO - Running <TaskInstance: 3_1_scheduled_dag.fetch_events scheduled__2019-01-03T00:00:00+00:00 [running]> on host b8db81cc5447
[2022-06-20 01:34:20,190] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=3_1_scheduled_dag
AIRFLOW_CTX_TASK_ID=fetch_events
AIRFLOW_CTX_EXECUTION_DATE=2019-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-03T00:00:00+00:00
[2022-06-20 01:34:20,195] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-20 01:34:20,197] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p /data/events && curl -o /data/events.json http://events_api:5000/events']
[2022-06-20 01:34:20,211] {subprocess.py:85} INFO - Output:
[2022-06-20 01:34:20,214] {subprocess.py:92} INFO - mkdir: cannot create directory ‘/data’: Permission denied
[2022-06-20 01:34:20,216] {subprocess.py:96} INFO - Command exited with return code 1
[2022-06-20 01:34:20,301] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-06-20 01:34:20,312] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=3_1_scheduled_dag, task_id=fetch_events, execution_date=20190103T000000, start_date=20220620T013420, end_date=20220620T013420
[2022-06-20 01:34:20,360] {standard_task_runner.py:97} ERROR - Failed to execute job 24 for task fetch_events (Bash command failed. The command returned a non-zero exit code 1.; 173)
[2022-06-20 01:34:20,407] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:34:20,605] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
